### PR TITLE
Aecom noise vibration

### PR DESCRIPTION
**Pull request by ramod8**

### CODE REVIEW

**Comment by abonstu** [comment]
@ramod8 we can either make these converters **public** (everyone sees the option in the datasource wizard) or **private** (selectively enabled on a customers account via the admin panel); we choose this based on whether the converter is generic (e.g. works with ALL Aecom Noise units) and whether the converter is useful to the wider eagle.io community (i.e. is the unit rarely seen in the wild or could is likely to be used by other customers)

which seems most appropriate to you in this case?

**Comment by ramod8** [comment]
@abonstu , these will be private because it depends on a specific way the device is configured. However let me take a look to see if theres a way to make it more generic so other people could use them.

**Comment by abonstu** [comment]
if you can make it generic fantastic, but no big deal if you cant (just make the converter **private**).

the second component to the decision is: will it only be used by Aecom or is there a solid likelihood other customers will be using this hardware? we dont want to make the converter **public** (and make the UI more complex) if no one but Aecom is really going to use it.

take a look at `template.yml`, that describes how to instantiate the function (and choose the visibility)

**Comment by ramod8** [comment]
ok, I updated the template to make it private. Can we publish this now and I will just enable it on argos? I can work on seeing if this can be generic in parallel and update accordingly

**Pull request merged**
