### PR TITLE
dacortexjson

### PR DESCRIPTION
**Pull request by beol74**
pull request for a converter desgined for company internal JSON format. 
-input file submitted 
-test passed 
- JSLint check OK

### CODE REVIEW

**Comment by abonstu** [comment]
eslint has now been configured to execute as tests are run, please pull the latest changes and run 'npm run test' to ensure tests and lint pass without errors

**Comment by beol74** [comment]
latest changes from master pulled and new version of 'npm run test' passed succesfully

**Comment by abonstu** [comment]
im seeing two lint errors when i execute `npm run test`

```
> converter@1.0.0 lint
> eslint '**/*.ts' --quiet --fix


/Users/jarrah/src/converter/lib/dacortexjson/dacortexjson-converter.ts
  25:78  error  Expected '===' and instead saw '=='  eqeqeq
  27:66  error  Expected '===' and instead saw '=='  eqeqeq

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by beol74** [comment]
this is the message i get when running lint. Of course there is a .ts file in the folder.
 
> converter@1.0.0 lint
> eslint '**/*.ts' --quiet --fix


Oops! Something went wrong! :(

ESLint: 8.22.0

No files matching the pattern "'**/*.ts'" were found.
Please check for typing mistakes in the pattern.

**Comment by abonstu** [comment]
i've adjusted the eslint expression to remove the single quotes which may be an issue if you are using Microsoft Windows.

can you pull the latest and test again?

**Comment by beol74** [comment]
Indeed I am using windows. I'll try again

**Pull request merged**
